/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface LotteryInterface extends ethers.utils.Interface {
  functions: {
    "adminAddress()": FunctionFragment;
    "adminWithdraw(uint256)": FunctionFragment;
    "allocation(uint256)": FunctionFragment;
    "buy(uint256,uint8[4])": FunctionFragment;
    "claimReward(uint256)": FunctionFragment;
    "drawed()": FunctionFragment;
    "drawing(uint256)": FunctionFragment;
    "drawingPhase()": FunctionFragment;
    "egg()": FunctionFragment;
    "enterDrawingPhase()": FunctionFragment;
    "generateCombinations(uint8[4])": FunctionFragment;
    "getMatchingRewardAmount(uint256,uint256)": FunctionFragment;
    "getRewardView(uint256)": FunctionFragment;
    "getTotalRewards(uint256)": FunctionFragment;
    "historyAmount(uint256,uint256)": FunctionFragment;
    "historyNumbers(uint256,uint256)": FunctionFragment;
    "initialize(address,address,uint256,uint8,address)": FunctionFragment;
    "issueIndex()": FunctionFragment;
    "lastTimestamp()": FunctionFragment;
    "lotteryInfo(uint256,uint256)": FunctionFragment;
    "lotteryNFT()": FunctionFragment;
    "maxNumber()": FunctionFragment;
    "minPrice()": FunctionFragment;
    "multiBuy(uint256,uint8[4][])": FunctionFragment;
    "multiClaim(uint256[])": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reset()": FunctionFragment;
    "setAdmin(address)": FunctionFragment;
    "setAllocation(uint8,uint8,uint8)": FunctionFragment;
    "setMaxNumber(uint8)": FunctionFragment;
    "setMinPrice(uint256)": FunctionFragment;
    "totalAddresses()": FunctionFragment;
    "totalAmount()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "userBuyAmountSum(uint256,uint64)": FunctionFragment;
    "userInfo(address,uint256)": FunctionFragment;
    "winningNumbers(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "adminAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allocation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "drawed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "drawing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "drawingPhase",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "egg", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "enterDrawingPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generateCombinations",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchingRewardAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardView",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "historyAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "historyNumbers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "issueIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryNFT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxNumber", values?: undefined): string;
  encodeFunctionData(functionFragment: "minPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multiBuy",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiClaim",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reset", values?: undefined): string;
  encodeFunctionData(functionFragment: "setAdmin", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setAllocation",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userBuyAmountSum",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winningNumbers",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allocation", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drawed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drawing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drawingPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "egg", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enterDrawingPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateCombinations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchingRewardAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "historyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "historyNumbers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issueIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lotteryNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxNumber", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiBuy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBuyAmountSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningNumbers",
    data: BytesLike
  ): Result;

  events: {
    "Buy(address,uint256)": EventFragment;
    "Claim(address,uint256,uint256)": EventFragment;
    "DevWithdraw(address,uint256)": EventFragment;
    "Drawing(uint256,uint8[4])": EventFragment;
    "MultiBuy(address,uint256)": EventFragment;
    "MultiClaim(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Reset(uint256)": EventFragment;
    "SetAdmin(address,address)": EventFragment;
    "SetAllocation(address,uint8,uint8,uint8)": EventFragment;
    "SetMaxNumber(address,uint256)": EventFragment;
    "SetMinPrice(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Buy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DevWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Drawing"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MultiBuy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MultiClaim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Reset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAdmin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAllocation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxNumber"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMinPrice"): EventFragment;
}

export class Lottery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LotteryInterface;

  functions: {
    adminAddress(overrides?: CallOverrides): Promise<[string]>;

    adminWithdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    allocation(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    buy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimReward(
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    drawed(overrides?: CallOverrides): Promise<[boolean]>;

    drawing(
      _externalRandomNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    drawingPhase(overrides?: CallOverrides): Promise<[boolean]>;

    egg(overrides?: CallOverrides): Promise<[string]>;

    enterDrawingPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    generateCombinations(
      number: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        [
          number,
          number,
          number,
          number,
          number,
          number,
          number,
          number,
          number,
          number,
          number
        ]
      ]
    >;

    getMatchingRewardAmount(
      _issueIndex: BigNumberish,
      _matchingNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRewardView(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTotalRewards(
      _issueIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    historyAmount(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    historyNumbers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    initialize(
      _egg: string,
      _lottery: string,
      _minPrice: BigNumberish,
      _maxNumber: BigNumberish,
      _adminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    issueIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    lotteryInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lotteryNFT(overrides?: CallOverrides): Promise<[string]>;

    maxNumber(overrides?: CallOverrides): Promise<[number]>;

    minPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    multiBuy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish][],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    multiClaim(
      _tickets: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAdmin(
      _adminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAllocation(
      _allcation1: BigNumberish,
      _allcation2: BigNumberish,
      _allcation3: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxNumber(
      _maxNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalAddresses(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userBuyAmountSum(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    winningNumbers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;
  };

  adminAddress(overrides?: CallOverrides): Promise<string>;

  adminWithdraw(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  allocation(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

  buy(
    _price: BigNumberish,
    _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimReward(
    _tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  drawed(overrides?: CallOverrides): Promise<boolean>;

  drawing(
    _externalRandomNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  drawingPhase(overrides?: CallOverrides): Promise<boolean>;

  egg(overrides?: CallOverrides): Promise<string>;

  enterDrawingPhase(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  generateCombinations(
    number: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number
    ]
  >;

  getMatchingRewardAmount(
    _issueIndex: BigNumberish,
    _matchingNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRewardView(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalRewards(
    _issueIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  historyAmount(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  historyNumbers(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  initialize(
    _egg: string,
    _lottery: string,
    _minPrice: BigNumberish,
    _maxNumber: BigNumberish,
    _adminAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  issueIndex(overrides?: CallOverrides): Promise<BigNumber>;

  lastTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  lotteryInfo(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lotteryNFT(overrides?: CallOverrides): Promise<string>;

  maxNumber(overrides?: CallOverrides): Promise<number>;

  minPrice(overrides?: CallOverrides): Promise<BigNumber>;

  multiBuy(
    _price: BigNumberish,
    _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish][],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  multiClaim(
    _tickets: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  reset(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAdmin(
    _adminAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAllocation(
    _allcation1: BigNumberish,
    _allcation2: BigNumberish,
    _allcation3: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxNumber(
    _maxNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinPrice(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalAddresses(overrides?: CallOverrides): Promise<BigNumber>;

  totalAmount(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userBuyAmountSum(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userInfo(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  winningNumbers(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    adminAddress(overrides?: CallOverrides): Promise<string>;

    adminWithdraw(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    allocation(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

    buy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<void>;

    claimReward(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    drawed(overrides?: CallOverrides): Promise<boolean>;

    drawing(
      _externalRandomNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    drawingPhase(overrides?: CallOverrides): Promise<boolean>;

    egg(overrides?: CallOverrides): Promise<string>;

    enterDrawingPhase(overrides?: CallOverrides): Promise<void>;

    generateCombinations(
      number: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
      ]
    >;

    getMatchingRewardAmount(
      _issueIndex: BigNumberish,
      _matchingNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardView(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalRewards(
      _issueIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    historyAmount(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    historyNumbers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    initialize(
      _egg: string,
      _lottery: string,
      _minPrice: BigNumberish,
      _maxNumber: BigNumberish,
      _adminAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    issueIndex(overrides?: CallOverrides): Promise<BigNumber>;

    lastTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    lotteryInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lotteryNFT(overrides?: CallOverrides): Promise<string>;

    maxNumber(overrides?: CallOverrides): Promise<number>;

    minPrice(overrides?: CallOverrides): Promise<BigNumber>;

    multiBuy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish][],
      overrides?: CallOverrides
    ): Promise<void>;

    multiClaim(
      _tickets: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    reset(overrides?: CallOverrides): Promise<void>;

    setAdmin(_adminAddress: string, overrides?: CallOverrides): Promise<void>;

    setAllocation(
      _allcation1: BigNumberish,
      _allcation2: BigNumberish,
      _allcation3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxNumber(
      _maxNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinPrice(_price: BigNumberish, overrides?: CallOverrides): Promise<void>;

    totalAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    totalAmount(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userBuyAmountSum(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winningNumbers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {
    Buy(
      user?: string | null,
      tokenId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { user: string; tokenId: BigNumber }
    >;

    Claim(
      user?: string | null,
      tokenid?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { user: string; tokenid: BigNumber; amount: BigNumber }
    >;

    DevWithdraw(
      user?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { user: string; amount: BigNumber }
    >;

    Drawing(
      issueIndex?: BigNumberish | null,
      winningNumbers?: null
    ): TypedEventFilter<
      [BigNumber, [number, number, number, number]],
      {
        issueIndex: BigNumber;
        winningNumbers: [number, number, number, number];
      }
    >;

    MultiBuy(
      user?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { user: string; amount: BigNumber }
    >;

    MultiClaim(
      user?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { user: string; amount: BigNumber }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    Reset(
      issueIndex?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { issueIndex: BigNumber }>;

    SetAdmin(
      user?: string | null,
      admin?: string | null
    ): TypedEventFilter<[string, string], { user: string; admin: string }>;

    SetAllocation(
      user?: string | null,
      allocation1?: null,
      allocation2?: null,
      allocation3?: null
    ): TypedEventFilter<
      [string, number, number, number],
      {
        user: string;
        allocation1: number;
        allocation2: number;
        allocation3: number;
      }
    >;

    SetMaxNumber(
      user?: string | null,
      number?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { user: string; number: BigNumber }
    >;

    SetMinPrice(
      user?: string | null,
      price?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { user: string; price: BigNumber }
    >;
  };

  estimateGas: {
    adminAddress(overrides?: CallOverrides): Promise<BigNumber>;

    adminWithdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    allocation(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimReward(
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    drawed(overrides?: CallOverrides): Promise<BigNumber>;

    drawing(
      _externalRandomNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    drawingPhase(overrides?: CallOverrides): Promise<BigNumber>;

    egg(overrides?: CallOverrides): Promise<BigNumber>;

    enterDrawingPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    generateCombinations(
      number: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMatchingRewardAmount(
      _issueIndex: BigNumberish,
      _matchingNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardView(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalRewards(
      _issueIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    historyAmount(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    historyNumbers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _egg: string,
      _lottery: string,
      _minPrice: BigNumberish,
      _maxNumber: BigNumberish,
      _adminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    issueIndex(overrides?: CallOverrides): Promise<BigNumber>;

    lastTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    lotteryInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lotteryNFT(overrides?: CallOverrides): Promise<BigNumber>;

    maxNumber(overrides?: CallOverrides): Promise<BigNumber>;

    minPrice(overrides?: CallOverrides): Promise<BigNumber>;

    multiBuy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish][],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    multiClaim(
      _tickets: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAdmin(
      _adminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAllocation(
      _allcation1: BigNumberish,
      _allcation2: BigNumberish,
      _allcation3: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxNumber(
      _maxNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    totalAmount(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userBuyAmountSum(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winningNumbers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adminAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    adminWithdraw(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    allocation(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimReward(
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    drawed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    drawing(
      _externalRandomNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    drawingPhase(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    egg(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    enterDrawingPhase(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    generateCombinations(
      number: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMatchingRewardAmount(
      _issueIndex: BigNumberish,
      _matchingNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardView(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalRewards(
      _issueIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    historyAmount(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    historyNumbers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _egg: string,
      _lottery: string,
      _minPrice: BigNumberish,
      _maxNumber: BigNumberish,
      _adminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    issueIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lotteryInfo(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lotteryNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multiBuy(
      _price: BigNumberish,
      _numbers: [BigNumberish, BigNumberish, BigNumberish, BigNumberish][],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    multiClaim(
      _tickets: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAdmin(
      _adminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAllocation(
      _allcation1: BigNumberish,
      _allcation2: BigNumberish,
      _allcation3: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxNumber(
      _maxNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalAddresses(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userBuyAmountSum(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winningNumbers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
